#!/usr/bin/perl
#
# chat
#
# Copyright (c) 2010 - The OpenSplash Team
# http://www.opensplash-project.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

use Net::DBus;
#use Net::DBus::Reactor;

my $message = $ARGV[0];

my $chat = Net::DBus->session
	->get_service('org.opensplash.bot')
	->get_object('/org/opensplash/bot/Chat')
;

my $greeting = $chat->hello($message);
print "$greeting\n";

