#!/bin/bash
#
# command
#
# Copyright (c) 2010-2011  The OpenSplash Team
# http://www.opensplash-project.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

command=$*
user=
datetime=

# handle datetime here
# strip action here

command=$(echo $command | sed -e 's/run//i' -e 's/execute//i')


for program in $command; do
	which $program
	if [ $? == 0 ]; then
		nohup $program > /dev/null &
	fi
done;

