#!/bin/sh
wget http://www.alicebot.org/aiml/aaa/Adverbs.aiml -O Adverbs.aiml
wget http://www.alicebot.org/aiml/aaa/AI.aiml -O AI.aiml
wget http://www.alicebot.org/aiml/aaa/ALICE.aiml -O ALICE.aiml
wget http://www.alicebot.org/aiml/aaa/Astrology.aiml -O Astrology.aiml
wget http://www.alicebot.org/aiml/aaa/Atomic.aiml -O Atomic.aiml
wget http://www.alicebot.org/aiml/aaa/Badanswer.aiml -O Badanswer.aiml
wget http://www.alicebot.org/aiml/aaa/Biography.aiml -O Biography.aiml
wget http://www.alicebot.org/aiml/aaa/Blackjack.aiml -O Blackjack.aiml
wget http://www.alicebot.org/aiml/aaa/Bot.aiml -O Bot.aiml
wget http://www.alicebot.org/aiml/aaa/Botmaster.aiml -O Botmaster.aiml
wget http://www.alicebot.org/aiml/aaa/Client.aiml -O Client.aiml
wget http://www.alicebot.org/aiml/aaa/Computers.aiml -O Computers.aiml
wget http://www.alicebot.org/aiml/aaa/Date.aiml -O Date.aiml
wget http://www.alicebot.org/aiml/aaa/Default.aiml -O Default.aiml
wget http://www.alicebot.org/aiml/aaa/Dialog.aiml -O Dialog.aiml
wget http://www.alicebot.org/aiml/aaa/Drugs.aiml -O Drugs.aiml
wget http://www.alicebot.org/aiml/aaa/Emotion.aiml -O Emotion.aiml
wget http://www.alicebot.org/aiml/aaa/Food.aiml -O Food.aiml
wget http://www.alicebot.org/aiml/aaa/Geography.aiml -O Geography.aiml
wget http://www.alicebot.org/aiml/aaa/Gossip.aiml -O Gossip.aiml
wget http://www.alicebot.org/aiml/aaa/Happy.aiml -O Happy.aiml
wget http://www.alicebot.org/aiml/aaa/History.aiml -O History.aiml
wget http://www.alicebot.org/aiml/aaa/Human.aiml -O Human.aiml
wget http://www.alicebot.org/aiml/aaa/Humor.aiml -O Humor.aiml
wget http://www.alicebot.org/aiml/aaa/Inquiry.aiml -O Inquiry.aiml
wget http://www.alicebot.org/aiml/aaa/Integer.aiml -O Integer.aiml
wget http://www.alicebot.org/aiml/aaa/Interjection.aiml -O Interjection.aiml
wget http://www.alicebot.org/aiml/aaa/IU.aiml -O IU.aiml
wget http://www.alicebot.org/aiml/aaa/Knowledge.aiml -O Knowledge.aiml
wget http://www.alicebot.org/aiml/aaa/Literature.aiml -O Literature.aiml
wget http://www.alicebot.org/aiml/aaa/Luckyslots.aiml -O Luckyslots.aiml
wget http://www.alicebot.org/aiml/aaa/Money.aiml -O Money.aiml
wget http://www.alicebot.org/aiml/aaa/Movies.aiml -O Movies.aiml
wget http://www.alicebot.org/aiml/aaa/Multiple.aiml -O Multiple.aiml
wget http://www.alicebot.org/aiml/aaa/Music.aiml -O Music.aiml
wget http://www.alicebot.org/aiml/aaa/Parts.aiml -O Parts.aiml
wget http://www.alicebot.org/aiml/aaa/Personality.aiml -O Personality.aiml
wget http://www.alicebot.org/aiml/aaa/Philosophy.aiml -O Philosophy.aiml
wget http://www.alicebot.org/aiml/aaa/Pickup.aiml -O Pickup.aiml
wget http://www.alicebot.org/aiml/aaa/Politics.aiml -O Politics.aiml
wget http://www.alicebot.org/aiml/aaa/Predicates.aiml -O Predicates.aiml
wget http://www.alicebot.org/aiml/aaa/Psychology.aiml -O Psychology.aiml
wget http://www.alicebot.org/aiml/aaa/Reduce.aiml -O Reduce.aiml
wget http://www.alicebot.org/aiml/aaa/Reducer.aiml -O Reducer.aiml
wget http://www.alicebot.org/aiml/aaa/Reductions.aiml -O Reductions.aiml
wget http://www.alicebot.org/aiml/aaa/Religion.aiml -O Religion.aiml
wget http://www.alicebot.org/aiml/aaa/Salutations.aiml -O Salutations.aiml
wget http://www.alicebot.org/aiml/aaa/Science.aiml -O Science.aiml
wget http://www.alicebot.org/aiml/aaa/Sex.aiml -O Sex.aiml
wget http://www.alicebot.org/aiml/aaa/Spam.aiml -O Spam.aiml
wget http://www.alicebot.org/aiml/aaa/Sports.aiml -O Sports.aiml
wget http://www.alicebot.org/aiml/aaa/Stack.aiml -O Stack.aiml
wget http://www.alicebot.org/aiml/aaa/Stories.aiml -O Stories.aiml
wget http://www.alicebot.org/aiml/aaa/That.aiml -O That.aiml
wget http://www.alicebot.org/aiml/aaa/update.aiml -O update.aiml
wget http://www.alicebot.org/aiml/aaa/Utilities.aiml -O Utilities.aiml
wget http://www.alicebot.org/aiml/aaa/Wallace.aiml -O Wallace.aiml
wget http://www.alicebot.org/aiml/aaa/Wordplay.aiml -O Wordplay.aiml
wget http://www.alicebot.org/aiml/aaa/Xfind.aiml -O Xfind.aiml
