#!/usr/bin/perl
#
# splashbox-daemon
#
# Copyright (c) 2010 - The OpenSplash Team
# http://www.opensplash-project.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Proc::Daemon;
use Proc::PID::File;
use XML::Simple;
use Data::Dumper;

my $DIR_XML='/tmp/splashbox';
my $BOT_PATH='../action/';
my @jobs;
my $xml = new XML::Simple;

sub check_job {
	@jobs = <$DIR_XML/now/*.xml>;
	foreach my $thisjob (@jobs) {
#		print "$thisjob\n";
		my $data = $xml->XMLin("$thisjob");
#		print Dumper($data);
		my $user = $data->{'data'}->{'user'};
		my $robot = $data->{'meta'}->{'robot'};
		my $raw = $data->{'data'}->{'raw'};

		# Call robot.
		printf STDERR ("%s runs '%s %s'\n", $user, $BOT_PATH . $robot, $raw);
		system("$BOT_PATH$robot '$raw'");

		unlink $thisjob;
	}
}

if (defined $ARGV[0] && $ARGV[0] eq "-d")
{
	$ENV{USER} eq 'root' || print STDERR "You must be root to run it as a daemon.\n";
	Proc::Daemon::Init;
	if (Proc::PID::File->running()) {
		print STDERR "Daemon is already running.\n";
		exit(0);
	}
}

my $continue = 1;
$SIG{TERM} = sub { $continue = 0 };


while ($continue) {
	&check_job;
	sleep 10;
}

print STDERR "Daemon stopped.";
